
use strict;
use warnings;

use Module::Build 0.3601;


my %module_build_args = (
  "build_requires" => {
    "Module::Build" => "0.3601"
  },
  "configure_requires" => {
    "Module::Build" => "0.3601"
  },
  "dist_abstract" => "Patch module for LWP::UserAgent",
  "dist_author" => [
    "Steven Haryanto <stevenharyanto\@gmail.com>"
  ],
  "dist_name" => "LWP-UserAgent-patch-log_response",
  "dist_version" => "0.03",
  "license" => "perl",
  "module_name" => "LWP::UserAgent::patch::log_response",
  "recommends" => {},
  "recursive_test_files" => 1,
  "requires" => {
    "LWP::UserAgent" => "6.04",
    "Log::Any" => 0,
    "Module::Patch" => "0.10",
    "perl" => "5.010001"
  },
  "script_files" => []
);


my $build = Module::Build->new(%module_build_args);

$build->create_build_script;
